services:
  postgres:
    image: postgres:16-alpine
    container_name: splitters-db
    restart: unless-stopped
    networks:
      - traefik-network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - splitters_postgres_data:/var/lib/postgresql/data

  app:
    image: leesavage09/splitters
    container_name: splitters
    restart: unless-stopped
    networks:
      - traefik-network
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.splitters.rule=Host(`splitters.exp.leesavage.co.uk`)'
      - 'traefik.http.routers.splitters.entrypoints=websecure'
      - 'traefik.http.routers.splitters.tls=true'
      - 'traefik.http.routers.splitters.tls.certresolver=le'
      - 'traefik.http.services.splitters.loadbalancer.server.port=3000'
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      VITE_API_URL: ${VITE_API_URL}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - postgres
    command: sh -c "node dist/src/main.js"

volumes:
  splitters_postgres_data:

networks:
  traefik-network:
    external: true
