services:
  postgres:
    image: postgres:16-alpine
    container_name: splitters-db
    restart: unless-stopped
    networks:
      - backend
    env_file:
      - .env
    volumes:
      - splitters_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d splitters_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: leesavage09/splitters
    container_name: splitters
    restart: unless-stopped
    # ports:
    #   - "3000:3000"
    networks:
      - backend
      - traefik-network
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.splitters.rule=Host(`splitters.exp.leesavage.co.uk`)'
      - 'traefik.http.routers.splitters.entrypoints=websecure'
      - 'traefik.http.routers.splitters.tls=true'
      - 'traefik.http.routers.splitters.tls.certresolver=le'
      - 'traefik.http.services.splitters.loadbalancer.server.port=3000'
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "npx prisma migrate deploy && node dist/src/main.js"

volumes:
  splitters_postgres_data:

networks:
  backend:
  traefik-network:
    external: true
